// context/types/actionTypes.js

export const ActionTypes = {
  // Loading states
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',

  // Data actions
  SET_ITEMS: 'SET_ITEMS',
  ADD_ITEM: 'ADD_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',

  SET_SUPPLIERS: 'SET_SUPPLIERS',
  ADD_SUPPLIER: 'ADD_SUPPLIER',
  UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
  DELETE_SUPPLIER: 'DELETE_SUPPLIER',
  SELECT_SUPPLIER: 'SELECT_SUPPLIER',

  SET_CUSTOMERS: 'SET_CUSTOMERS',
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',
  SELECT_CUSTOMER: 'SELECT_CUSTOMER',

  SET_PURCHASES: 'SET_PURCHASES',
  ADD_PURCHASE: 'ADD_PURCHASE',
  UPDATE_PURCHASE: 'UPDATE_PURCHASE',
  DELETE_PURCHASE: 'DELETE_PURCHASE',

  SET_SALES: 'SET_SALES',
  ADD_SALE: 'ADD_SALE',
  UPDATE_SALE: 'UPDATE_SALE',
  DELETE_SALE: 'DELETE_SALE',

  SET_EXPENSES: 'SET_EXPENSES',
  ADD_EXPENSE: 'ADD_EXPENSE',
  UPDATE_EXPENSE: 'UPDATE_EXPENSE',
  DELETE_EXPENSE: 'DELETE_EXPENSE',

  SET_PAYMENTS: 'SET_PAYMENTS',
  ADD_PAYMENT: 'ADD_PAYMENT',
  UPDATE_PAYMENT: 'UPDATE_PAYMENT', // ADDED: For updating existing payments
  DELETE_PAYMENT: 'DELETE_PAYMENT', // ADDED: For deleting payments

  SET_RECEIPTS: 'SET_RECEIPTS',
  ADD_RECEIPT: 'ADD_RECEIPT',
  UPDATE_RECEIPT: 'UPDATE_RECEIPT', // ADDED: For updating existing receipts
  DELETE_RECEIPT: 'DELETE_RECEIPT', // ADDED: For deleting receipts

  // New models added to action types
  SET_TRANSACTIONS: 'SET_TRANSACTIONS',
  ADD_TRANSACTION: 'ADD_TRANSACTION',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',

  SET_ACCOUNTS: 'SET_ACCOUNTS',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',

  SET_EXPENSE_CATEGORIES: 'SET_EXPENSE_CATEGORIES',
  ADD_EXPENSE_CATEGORY: 'ADD_EXPENSE_CATEGORY',
  UPDATE_EXPENSE_CATEGORY: 'UPDATE_EXPENSE_CATEGORY',
  DELETE_EXPENSE_CATEGORY: 'DELETE_EXPENSE_CATEGORY',

  SET_CASH_BOOK_ENTRIES: 'SET_CASH_BOOK_ENTRIES', // Renamed for clarity for individual entries
  ADD_CASH_BOOK_ENTRY: 'ADD_CASH_BOOK_ENTRY',
  UPDATE_CASH_BOOK_ENTRY: 'UPDATE_CASH_BOOK_ENTRY',
  DELETE_CASH_BOOK_ENTRY: 'DELETE_CASH_BOOK_ENTRY',

  SET_BANK_TRANSACTIONS: 'SET_BANK_TRANSACTIONS',
  ADD_BANK_TRANSACTION: 'ADD_BANK_TRANSACTION',
  UPDATE_BANK_TRANSACTION: 'UPDATE_BANK_TRANSACTION',
  DELETE_BANK_TRANSACTION: 'DELETE_BANK_TRANSACTION',

  SET_REPORTING_PERIODS: 'SET_REPORTING_PERIODS',
  ADD_REPORTING_PERIOD: 'ADD_REPORTING_PERIOD',
  UPDATE_REPORTING_PERIOD: 'UPDATE_REPORTING_PERIOD',
  DELETE_REPORTING_PERIOD: 'DELETE_REPORTING_PERIOD',

  SET_INVENTORY_SNAPSHOTS: 'SET_INVENTORY_SNAPSHOTS',
  ADD_INVENTORY_SNAPSHOT: 'ADD_INVENTORY_SNAPSHOT',
  UPDATE_INVENTORY_SNAPSHOT: 'UPDATE_INVENTORY_SNAPSHOT',
  DELETE_INVENTORY_SNAPSHOT: 'DELETE_INVENTORY_SNAPSHOT',

  UPDATE_STATS: 'UPDATE_STATS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
};